### ISSUE TITLE
PASCAL VOC dataset settings

### ISSUE THREAD

**Issue by prinshul** [facebookresearch/unbiased-teacher#5]
Can you please mention the settings for PASCAL VOC dataset like Image size, batch size (labeled/unlabeled), total iterations, epochs?

**Comment by ycliu93** [comment]
Here are the details of VOC experiments. You could directly use the following parameters in your config files. 
```
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
SOLVER:
  MAX_ITER: 180000 
  IMG_PER_BATCH_LABEL: 32
  IMG_PER_BATCH_UNLABEL: 32
  BASE_LR: 0.001
```

For other parameters, you could check the last page of the appendix.[https://arxiv.org/pdf/2102.09480.pdf]( https://arxiv.org/pdf/2102.09480.pdf)
